server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
      endpoint:
        health:
          show-details: ALWAYS
    greeting-service:
      greeting: "Ciao"
      default-value: "Mondo"
  