spring:
  application:
    name: rest_spring_boot_java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_boot_java?useTimezone=true&serverTimezone=UTC
    username: root
    password: rska2022
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  loggin:
   level:
     root: WARN
     # br.com.fulldevstacks: DEBUG

server:
  port: 8081
